- .gitmodules
- Makefile
- Makefile.sample
- Makefile.terraform.sample
- README.md
- bootstrap_terraform.py
- container-ecr-template-repository.tf.sample
- container-template-repository.tf.sample
- initial-commit.sh
- template-repository.tf.sample
- terraform-template-repository.tf.sample
- terraform.tf.j2
- terraform.tfvars.j2
Signed-off-by: Chris Scott-Thomas <chris.scott-thomas@burendo.com>
> Create templates, scripts, Makefiles

- azuredevops-demo.tf
- burendo-common-config.tf
- burendo-githooks.tf
- burendo-github-config.tf
- burendo-handbook.tf
- burendo-repo-template-container.tf
- burendo-repo-template-terraform.tf
- burendo-repo-template.tf
- burendo-saas.tf
- burendo-secrets-config.tf
- container-ecr-template-repository.tf.sample
- container-template-repository.tf.sample
- generator-aws-api.tf
- initial-commit.sh
- template-repository.tf.sample
- terraform-template-repository.tf.sample
Fixes pre "Pro" upgrade and minor templating issues.
* All Private repos have branch protection hashed out, until we establish a license.
* All `initial-commit` resources have been removed from imported repos as they are not required, and are only required by the pipeline.
* Removed status checks on patterns that do not yet exist.
* added visibility flag to templates as default `public`
> Tempalte update 120822

- burendo-saas.tf
- generator-aws-api.tf
* Set visibility to `public`
* Uncomment branch protection
> Converting repos to public

- .github/workflows/pull-request.yml
- .github/workflows/tf-merge.yml
- .github/workflows/tf-pull-request.yml
- .github/workflows/tf-push.yml
- bootstrap.py
- burendo-github-config.tf
- terraform.tfvars.j2
- variables.tf.j2
Create GitHub actions for managing GitHub config in an automated fashion.
> Create GitHub actions

- .github/workflows/tf-merge.yml
- .github/workflows/tf-push.yml
- burendo-common-config.tf
- burendo-github-config.tf
- burendo-secrets-config.tf
> update repos with common secrets for pipelines

- burendo-common-config.tf
- burendo-secrets-config.tf
> Fix silly mistake of adding every secret to a single repo

- .github/workflows/tf-pull-request.yml
> Add workflows path

- .github/workflows/tf-merge.yml
- .github/workflows/tf-pull-request.yml
Apply adjusted workflow pattern to ensure logging failures only occur at the right time.
> Fix workflow logging

- .github/workflows/tf-merge.yml
- .github/workflows/tf-pull-request.yml
- burendo-handbook-infrastructure.tf
Create Burendo Handbook Infrastructure repo.
> burendo-handbook-infrastructure repo

- users.tf
> remove Lee. Compromised account

- users.tf
> Add iamleec

- burendo-common-config.tf
- burendo-github-config.tf
- burendo-secrets-config.tf
- users.tf
- Add Brian Bayes
- Add Rowan Gill
- Shift CI user to assume CI role
> Update mgmt users

- bootstrap.py
- burendo-identity.tf
- locals.tf.j2
- Create repo to manage users, groups, policies, roles etc.
- Get new accounts secrets when bootstrapping.
- Consume new accounts secrets for use.
> Create iam repo

- .github/workflows/tf-merge.yml
- .github/workflows/tf-pull-request.yml
- Actions previously skipped Apply errors.  
- Add `sed` as CI should assume CI role
> Fix Actions 05092022

- .github/workflows/tf-merge.yml
- .github/workflows/tf-pull-request.yml
> Attempt to fix logging, expect merge action to fail, but logging succeed

- .github/workflows/tf-merge.yml
- .github/workflows/tf-pull-request.yml
> Always redact account numbers. Upload separate logs, with separate fails

- .github/workflows/tf-merge.yml
- .github/workflows/tf-pull-request.yml
> success seems to work, so why not failure?

- burendo-aws-org.tf
Create AWS Organisation and Account management repo
> EP-76 - Create AWS Org repo

- burendo-secrets-config.tf
> Add management context to github secrets

- users.tf
> Add paul butler

- users.tf
Adding Jordan Rochester to the org.
> Add our first non-engineering member to the org

- burendo-handbook.tf
- burendo-identity.tf
- burendo-secrets-config.tf
Protect main branch for private repos
> Protect main branch for private repos

- locals.tf.j2
> Consume new json structure for accounts

- burendo-aws-org.tf
> Add missing secret to Org repo

- burendo-aws-labs.tf
Signed-off-by: Connor Avery <connor.avery1@nhs.net>
> Create a repo for AWS Labs material

- burendo-handbook-private.tf
- burendo-handbook-public.tf
> Create repo for handbook content we do not want publicly available

- burendo-handbook.tf
> Rename handbook repo

- burendo-handbook-infrastructure.tf
> Add AWS secrets to handbook infra

- burendo-handbook-infrastructure.tf
Signed-off-by: Connor Avery <connor.avery1@nhs.net>
> Add dev account details to GHA secrets

- bootstrap.py
- burendo-secrets-config.tf
Signed-off-by: Connor Avery <connor.avery1@nhs.net>
> Add dev GHA secrets for github secrets config

- bad-community-toolkit.tf
- users.tf
> Add Gary Green

- burendo-dot-com.tf
- burendo-website.tf
> Create the Burendo dot come website repo

- stackedit.tf
- template-repository.tf.sample
- Add forked Stackedit repo, so we can potentially fix it and use it.
- Remove unused secret from base repo template
> Fork Stackedit

- burendo-aws-labs.tf
Signed-off-by: Connor Avery <55276424+connoravo@users.noreply.github.com>
> Change repo name

- users.tf
> Add luke to the Org/EP team

- users.tf
> RM Lee Clark

- stackedit.tf
> Add secrets for publishing Docker images

- stackedit.tf
- terraform.tfvars.j2
- variables.tf.j2
> missed one

- stackedit.tf
Add AWS creds so we can push images to AWS ECR.
> Add AWS credentials to Stackedit repo

- stackedit.tf
> Add AWS Role

- burendo-handbook-infrastructure.tf
- burendo-handbook-private.tf
- burendo-handbook-public.tf
Rename burendo handbook private file and enforce admins on handbook repos.
> Private rename

- burendo-academy.tf
- burendo-identity.tf
- external-collaborators.tf
Add external collaborators so they are tracked in code
> Add external collaborators so they are tracked in code

- README.md
- external-collaborators.tf
Add handbook access instructions to the readme and enable private access with no current users
> Add handbook access instructions to the readme and enable private access with no current users

- external-collaborators.tf
Give Joe Walker handbook write access
> Give Joe Walker handbook write access

- burendo-handbook-infrastructure.tf
Add github token to infra repo to allow it to checkout private repos
> Add github token to infra repo to allow it to checkout private repos

- burendo-handbook-infrastructure.tf
Add user secret to handbook infra repo
> Add user secret to handbook infra repo

- burendo-handbook-private.tf
Add GH token to private handbook repo
> Add GH token to private handbook repo

- .github/workflows/tf-merge.yml
- burendo-github-config.tf
- burendo-handbook-infrastructure.tf
- burendo-handbook-private.tf
- burendo-handbook-public.tf
- burendo-identity.tf
- burendo-secrets-config.tf
- burendo-secrets.tf
- container-ecr-template-repository.tf.sample
- container-template-repository.tf.sample
- terraform.tfvars.j2
- variables.tf.j2
Notify slack channel on failures for builds after merge, add the relevant secret to all the repos that we care about notifying failures on
> Notify slack channel on failures

- .github/workflows/tf-merge.yml
Fix the reporting step to make it a new job
> Fix the reporting step to make it a new job

- talks.tf
Adding the `talks` repo as discussed.
> Adding talks repo

- users.tf
Remove contractors and add comments
> Remove contractors and add comments

- .github/workflows/tf-merge.yml
- burendo-github-config.tf
- burendo-handbook-infrastructure.tf
- burendo-handbook-private.tf
- burendo-handbook-public.tf
- burendo-identity.tf
- burendo-secrets-config.tf
- burendo-secrets.tf
- container-ecr-template-repository.tf.sample
- container-template-repository.tf.sample
- terraform.tfvars.j2
- variables.tf.j2
Add engineering slack group id and better reporting of GHA success and failure
> Add engineering slack group id and better reporting

- burendo-handbook-private.tf
Remove the secrets tf is having issue with as they are not needed in this repo anyway
> Remove the secrets tf is having issue with

- burendo-handbook-private.tf
- burendo-secrets.tf
Remove incorrect repo name from secrets repo secrets and restore secrets that are not the actual issue
> Remove incorrect repo name from secrets repo secrets

- burendo-handbook-private.tf
- burendo-secrets.tf
Remove the problem secrets from both repos
> Remove the problem secrets from both repos

- burendo-common-config.tf
Add Slack reporting secrets to common config as it's a dependancy repo
> Add Slack reporting secrets

- external-collaborators.tf
- membership.tf
Remove invitations that have never been accepted in months
> Remove invitations that have never been accepted in months

- external-collaborators.tf
> Bex handbook access

- external-collaborators.tf
Add Kate as handbook contributor
> Add Kate as handbook contributor

- membership.tf
- users.tf
Remove Connor Avery & Paul Butler
> Rm oldusers290224

- membership.tf
- users.tf
> Add kd 290224

- membership.tf
- users.tf
Add Emily and Connor to github
> Add Emily and Connor to github

- burendo-secrets-config.tf
add on env name for consistency
> fix secret name for secrets config

- README.md
- external-collaborators.tf
Add Richard for Handbook access.
Fix Slack channel reference in README.
> Add Richard, fix README

- membership.tf
- users.tf
> Add Josh to GitHub

- membership.tf
> Add Paul G, replacing Zesh

- burendo-oddfellows-pt-apis.tf
- burendo-oddfellows-pt-frontend.tf
- burendo-oddfellows-pt-infra.tf
- users.tf
Add oddfellows repos for the prototype
> Add oddfellows pt repos

- external-collaborators.tf
* Remove stale external collaborators.
* Remove handbook collaborator that have left the business.
> Cleanup 090425

- .gitignore
- membership.tf
- users.tf
> Add Sam to GH org

- burendo-oddfellows-pt-apis.tf
- burendo-oddfellows-pt-frontend.tf
- burendo-oddfellows-pt-infra.tf
Make the oddfellows repos private
> Make the oddfellows repos private

- burendo-toolbox-infrastructure.tf
- container-ecr-template-repository.tf.sample
- container-template-repository.tf.sample
- template-repository.tf.sample
- terraform-template-repository.tf.sample
Add "optional" attribute that changes after apply, breaking the pipeline.
> Vuln alerts

- safeshout-frontend.tf
- safeshout-project-information.tf
> Add safeshout secrets

- membership.tf
- users.tf
> Add Nick Lefley

- safeshout-identity.tf
> Add safeshout identity repo

- safeshout-frontend.tf
- safeshout-infra.tf
- safeshout-project-information.tf
- terraform.tfvars.j2
- variables.tf.j2
Add SS dashboard user and pass GH secrets
> Add SS dashboard user and pass GH secrets

- safeshout-frontend.tf
- safeshout-infra.tf
- safeshout-project-information.tf
> Add GHA token to SS repos
